### ISSUE TITLE
Different results on UBC PhotoTourism datasets from the paper

### ISSUE THREAD

**Issue by binbin-xu** [lg-zhang/dynamic-soft-margin-pytorch#1]
Hi Linguang,

Thank you very much for open sourcing your code on the GitHub.  
I just tried your testing script with your pre-trained weights on UBC PhotoTourism Dataset. However, I found the testing results seem different from the number on the paper. Some get much better and some get much worse. 

Here are the results I tested on my computer.

- using `pretrained/notredame_float`, I get the result of 
```
11-29:16:20:27 INFO [test.py:106] FPR95-brown.yosemite = 1.3639999999999999%
11-29:16:20:27 INFO [test.py:106] FPR95-brown.liberty = 1.102%
```

- using `pretrained/liberty_float`, I get the result of 
```
11-29:16:27:16 INFO [test.py:106] FPR95-brown.yosemite = 1.526%
11-29:16:27:16 INFO [test.py:106] FPR95-brown.notredame = 0.336%
```

- using `pretrained/yosemite_float`, I get the result of 
```
11-29:16:28:03 INFO [test.py:106] FPR95-brown.liberty = 1.9460000000000002%
11-29:16:28:03 INFO [test.py:106] FPR95-brown.notredame = 0.7000000000000001%
```

Do you have any idea what may cause these differences. Thank you!

**Comment by lg-zhang** [comment]
Hi @binbin-xu, I retrained the models using the latest release of PyTorch so the numbers are slightly different.
